version: "3"
services:
    jekyll-serve:
        image: bretfisher/jekyll-serve
        container_name: jekyll-serve
        volumes:
            - .:/site
        environment:
            - JEKYLL_ENV=development
        ports:
            - 4000:4000